from __future__ import annotations

import shutil
from pathlib import Path

import cv2
import numpy as np
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
KEYFRAMES = ASSETS / "keyframes"
SIZE = 520

BASE_FRAME_COUNT = 6
INBETWEENS = 3
LOOP_ACTIONS = {"idle", "sleep"}
PINGPONG_ACTIONS = {"happy"}
ACTIONS = ["idle", "talk", "wave", "happy", "eat", "sleep"]
WEBP_DURATIONS = {
    "idle": 42,
    "talk": 42,
    "wave": 42,
    "happy": 42,
    "eat": 42,
    "sleep": 48,
}


def load_rgba(path: Path) -> np.ndarray:
    image = Image.open(path).convert("RGBA").resize((SIZE, SIZE), Image.Resampling.LANCZOS)
    return np.array(image, dtype=np.uint8)


def save_rgba(path: Path, frame: np.ndarray) -> None:
    Image.fromarray(np.clip(frame, 0, 255).astype(np.uint8), "RGBA").save(path)


def rgba_to_flow_rgb(frame: np.ndarray) -> np.ndarray:
    rgb = frame[:, :, :3].astype(np.float32)
    alpha = frame[:, :, 3:4].astype(np.float32) / 255.0
    bg = np.full_like(rgb, 240.0)
    comp = rgb * alpha + bg * (1.0 - alpha)
    return np.clip(comp, 0, 255).astype(np.uint8)


def remap_frame(frame: np.ndarray, flow: np.ndarray, scale: float) -> np.ndarray:
    h, w = flow.shape[:2]
    grid_x, grid_y = np.meshgrid(np.arange(w, dtype=np.float32), np.arange(h, dtype=np.float32))
    map_x = grid_x - flow[:, :, 0] * scale
    map_y = grid_y - flow[:, :, 1] * scale
    channels = []
    for channel in range(4):
        warped = cv2.remap(
            frame[:, :, channel],
            map_x,
            map_y,
            interpolation=cv2.INTER_LINEAR,
            borderMode=cv2.BORDER_CONSTANT,
            borderValue=0,
        )
        channels.append(warped)
    return np.stack(channels, axis=2)


def interpolate_pair(a: np.ndarray, b: np.ndarray, steps: int) -> list[np.ndarray]:
    rgb_a = rgba_to_flow_rgb(a)
    rgb_b = rgba_to_flow_rgb(b)
    gray_a = cv2.cvtColor(rgb_a, cv2.COLOR_RGB2GRAY)
    gray_b = cv2.cvtColor(rgb_b, cv2.COLOR_RGB2GRAY)
    flow_ab = cv2.calcOpticalFlowFarneback(gray_a, gray_b, None, 0.5, 4, 31, 4, 7, 1.5, 0)
    flow_ba = cv2.calcOpticalFlowFarneback(gray_b, gray_a, None, 0.5, 4, 31, 4, 7, 1.5, 0)

    frames: list[np.ndarray] = []
    for step in range(1, steps + 1):
        t = step / (steps + 1)
        wa = remap_frame(a, flow_ab, t).astype(np.float32)
        wb = remap_frame(b, flow_ba, 1.0 - t).astype(np.float32)
        blended = wa * (1.0 - t) + wb * t
        frames.append(np.clip(blended, 0, 255).astype(np.uint8))
    return frames


def action_key_sequence(action: str, keyframes: list[np.ndarray]) -> tuple[list[np.ndarray], bool]:
    if action in LOOP_ACTIONS:
        return keyframes + keyframes[-2:0:-1], True
    if action in PINGPONG_ACTIONS:
        return keyframes + keyframes[-2:0:-1], False
    return keyframes, False


def backup_keyframes(action: str) -> list[Path]:
    folder = KEYFRAMES / action
    folder.mkdir(parents=True, exist_ok=True)
    paths = []
    for index in range(1, BASE_FRAME_COUNT + 1):
        src = ASSETS / f"frame_{action}_{index:02d}.png"
        dst = folder / f"frame_{action}_{index:02d}.png"
        if src.exists() and not dst.exists():
            shutil.copy2(src, dst)
        paths.append(dst if dst.exists() else src)
    return paths


def make_high_fps_frames(action: str) -> list[np.ndarray]:
    key_paths = backup_keyframes(action)
    keyframes = [load_rgba(path) for path in key_paths]
    sequence, cyclic = action_key_sequence(action, keyframes)
    output: list[np.ndarray] = []
    pair_count = len(sequence) if cyclic else len(sequence) - 1
    for i in range(pair_count):
        a = sequence[i]
        b = sequence[(i + 1) % len(sequence)]
        output.append(a)
        output.extend(interpolate_pair(a, b, INBETWEENS))
    if not cyclic:
        output.append(sequence[-1])
    return output


def write_action_frames(action: str, frames: list[np.ndarray]) -> None:
    for old in ASSETS.glob(f"frame_{action}_*.png"):
        old.unlink()
    for index, frame in enumerate(frames, 1):
        save_rgba(ASSETS / f"frame_{action}_{index:02d}.png", frame)
    save_rgba(ASSETS / f"{action}_momo_poster.png", frames[0])


def write_manifest(counts: dict[str, int]) -> None:
    lines = ["# Generated by interpolate_action_frames.py", "FRAME_COUNTS = {"]
    for action in ACTIONS:
        lines.append(f'    "{action}": {counts[action]},')
    lines.append("}")
    (ASSETS / "frame_manifest.py").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    counts: dict[str, int] = {}
    for action in ACTIONS:
        frames = make_high_fps_frames(action)
        write_action_frames(action, frames)
        counts[action] = len(frames)
        print(f"{action}: {len(frames)} frames")
    write_manifest(counts)


if __name__ == "__main__":
    main()
